D04
Berea-CS-Courses/capstone-project-horinet pull request #12
Opened 2021-04-05 04:32 UTC by horinet

I forgot to create the pull request on Friday...

2021-04-07 21:24 UTC, smanalai requested changes
You have explained the tools that you will be using in the concept documentation and also have a comprehensive and detailed reflection and the changes and updates you have made so far. However, I do not see the first section of the midterm documentation which requires students to submit a screenshot of their working code with a brief one-sentence description of what the code is doing. Everything else looks good. I will request a change to submit the screenshot.

2021-04-07 22:42 UTC, horinet commented
I will add that in now.

2021-04-07 23:31 UTC, horinet commented
I added the necessary photos and explanations.

2021-04-09 17:47 UTC, smanalai approved these changes
You have added the missing section and everything else looks good. You can go ahead and merge these changes.

2021-04-09 18:39 UTC, merged